### ISSUE TITLE
Skivvy Slider plugin

### ISSUE THREAD

**Issue by ninthward** [atelierabbey/skivvy-slideshow#13]
PHP error code on line 145

**Comment by ninthward** [comment]
Fatal error: Cannot redeclare shortcode_slideshow() (previously declared in /home/hskis3/public_html/resin/wp-content/themes/Skivvy-master/lib/skivvy_shortcodes.php:197) in /home/hskis3/public_html/resin/wp-content/plugins/skivvy-slideshow-master/inc/lib/skivvy_slideshow.php on line 145

**Comment by SillyCoyote** [comment]
This has to do with the duplicate code found in Skivvy/lib/skivvy_shortcodes.php. This entire file will be removed at a later date. Shortcodes do not belong in themes. For now, go to the file and remove the code referenced in the theme
